version: 2

models:
  - name: orders_current
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: version
        data_tests:
          - not_null
      - name: knowledge_time
        data_tests:
          - not_null